"""GitHub Actions Remote Execution Backend — free remote runtime for universal mobile project-building.

This module provides the architecture and client for triggering remote work through
GitHub Actions — the cheapest/free practical remote execution path compatible with
the existing Jarvis + GitHub stack.

CLASSIFICATION: REQUIRES_BRYAN_SETUP
COST: FREE (GitHub Actions free tier: 2000 min/month for private repos; unlimited for public)
ACCOUNT REQUIRED: Existing GitHub account (no new account needed)
MACBOOK-OFF CAPABLE: Yes — GitHub runs workflows on GitHub-hosted runners, not on MacBook

WHAT GITHUB ACTIONS CAN DO FOR JARVIS:
  - Run pytest tests on any branch/commit
  - Run build commands (npm build, cargo build, etc.)
  - Run packaging/release checks
  - Generate diffs between branches
  - Store artifacts (test results, build outputs)
  - Post status back via GitHub API (Jarvis polls or receives webhook)
  - Run code review analysis tools
  - Execute any shell command in a sandboxed environment

WHAT IT CANNOT DO (hard limits):
  - Real-time interactive file editing (each workflow is a batch job)
  - Sub-second latency (job queuing adds 10-60s startup time)
  - Access private MacBook-local files (only repo content accessible)
  - Deploy to production without Bryan authorization (hard gate preserved)

SETUP REQUIRED FROM BRYAN:
  1. Replace .env GITHUB_TOKEN with valid Classic PAT (ghp_...) with scopes:
     - gist (for snapshot sync)
     - workflow (for triggering Actions)
     - repo (for repo access, diffs, logs)
  2. Create .github/workflows/jarvis-remote.yml in the repo
     (template generated by this module — does NOT auto-push)
  3. No new accounts needed — uses existing GitHub

WORKFLOW TEMPLATE (safe to generate, not auto-pushed):
  - Trigger: workflow_dispatch with inputs (task_type, task_params)
  - Steps: checkout → install deps → run task → upload artifact → post status
  - All runs are sandboxed on GitHub-hosted runners
  - No secrets exposed in logs (GitHub masks secrets)
  - Bryan authorizes all deploy steps via required_permissions

SECURITY:
  - No secrets in workflow YAML (use GitHub repository secrets)
  - Deploys remain hard-gated (require_approval in workflow)
  - No auto-push, no force-push, no destructive ops without Bryan gate

Sprint: Sprint 3 Consolidated Final Retest
"""

from __future__ import annotations

import json
import os
import ssl
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Remote execution backend options
# ---------------------------------------------------------------------------

class RemoteBackendClassification(str, Enum):
    FREE_AND_PRACTICAL_NOW = "FREE_AND_PRACTICAL_NOW"
    LOW_COST_AND_JUSTIFIED = "LOW_COST_AND_JUSTIFIED"
    REQUIRES_BRYAN_SETUP = "REQUIRES_BRYAN_SETUP"
    TOO_EXPENSIVE_NOT_JUSTIFIED = "TOO_EXPENSIVE_NOT_JUSTIFIED"
    BLOCKED_EXTERNAL_PROVIDER = "BLOCKED_EXTERNAL_PROVIDER"
    BLOCKED_SECURITY = "BLOCKED_SECURITY"


REMOTE_BACKEND_OPTIONS: List[Dict[str, Any]] = [
    {
        "name": "GitHub Actions (workflow_dispatch)",
        "classification": RemoteBackendClassification.REQUIRES_BRYAN_SETUP.value,
        "cost": "FREE — 2000 min/month for private repos, unlimited for public",
        "account_required": "Existing GitHub account",
        "macbook_off_capable": True,
        "repo_access": True,
        "can_run_tests": True,
        "can_run_builds": True,
        "can_store_artifacts": True,
        "can_view_logs": True,
        "deploy_gated": True,
        "setup_steps": [
            "1. Create .github/workflows/jarvis-remote.yml (template below)",
            "2. Replace .env GITHUB_TOKEN with PAT having: gist + workflow + repo scopes",
            "3. Add any build secrets to GitHub repository secrets (not .env)",
            "4. Jarvis mobile → POST /v1/remote/trigger-workflow → GitHub API",
            "5. Poll GET /v1/remote/workflow-status for result",
        ],
        "recommended": True,
        "reason": "Free, uses existing GitHub account and repo, sandboxed, Bryan-authorized",
        "latency": "10-60s job startup time — batch, not real-time",
    },
    {
        "name": "GitHub Codespaces",
        "classification": RemoteBackendClassification.REQUIRES_BRYAN_SETUP.value,
        "cost": "60 hours/month free for personal accounts",
        "account_required": "Existing GitHub account",
        "macbook_off_capable": True,
        "repo_access": True,
        "can_run_tests": True,
        "can_run_builds": True,
        "can_store_artifacts": True,
        "can_view_logs": True,
        "deploy_gated": True,
        "setup_steps": [
            "1. Open repo on github.com → Code → Codespaces → New codespace",
            "2. Access via browser (including mobile browser)",
            "3. Full VS Code environment in browser — no local install needed",
            "4. Not Jarvis-native — Bryan controls directly in browser",
        ],
        "recommended": False,
        "reason": "Not Jarvis-controlled — Bryan operates directly. Not integrated into pipeline.",
        "latency": "30-60s startup",
    },
    {
        "name": "Tailscale + always-on machine",
        "classification": RemoteBackendClassification.REQUIRES_BRYAN_SETUP.value,
        "cost": "FREE for personal use (up to 3 users)",
        "account_required": "Tailscale account (free)",
        "macbook_off_capable": True,
        "repo_access": True,
        "can_run_tests": True,
        "can_run_builds": True,
        "can_store_artifacts": True,
        "can_view_logs": True,
        "deploy_gated": True,
        "setup_steps": [
            "1. Install Tailscale on the always-on machine (e.g. home server, Raspberry Pi, cloud VM)",
            "2. Install Tailscale on iPhone",
            "3. Both join same Tailscale network",
            "4. Run Jarvis FastAPI server on always-on machine",
            "5. Mobile connects to always-on machine via Tailscale IP",
        ],
        "recommended": False,
        "reason": "Requires Bryan to have an always-on machine. Good if one exists.",
        "latency": "Near real-time if machine is running",
    },
    {
        "name": "Self-hosted GitHub Actions runner",
        "classification": RemoteBackendClassification.REQUIRES_BRYAN_SETUP.value,
        "cost": "FREE — self-hosted runners have no minute limits",
        "account_required": "Existing GitHub account",
        "macbook_off_capable": False,
        "repo_access": True,
        "can_run_tests": True,
        "can_run_builds": True,
        "can_store_artifacts": True,
        "can_view_logs": True,
        "deploy_gated": True,
        "setup_steps": [
            "1. Download GitHub Actions runner on always-on machine",
            "2. Register runner in repo settings",
            "3. Workflows run on Bryan's hardware (not GitHub-hosted)",
        ],
        "recommended": False,
        "reason": "Requires always-on machine. MacBook-off only if other machine is always on.",
        "latency": "Near real-time if runner online",
    },
    {
        "name": "Fly.io (containerized workers)",
        "classification": RemoteBackendClassification.LOW_COST_AND_JUSTIFIED.value,
        "cost": "$0–$5/month on free/hobby tier",
        "account_required": "Fly.io account (free tier available)",
        "macbook_off_capable": True,
        "repo_access": True,
        "can_run_tests": True,
        "can_run_builds": True,
        "can_store_artifacts": True,
        "can_view_logs": True,
        "deploy_gated": True,
        "setup_steps": [
            "1. flyctl auth login",
            "2. flyctl launch in repo",
            "3. Deploy Jarvis FastAPI server as Fly app",
            "4. Mobile connects to Fly app URL",
        ],
        "recommended": False,
        "reason": "Good option if Bryan wants persistent always-on API. Low cost. Not free.",
        "latency": "Near real-time",
    },
    {
        "name": "GitHub API (direct repo ops without Actions)",
        "classification": RemoteBackendClassification.FREE_AND_PRACTICAL_NOW.value,
        "cost": "FREE — GitHub API rate limits are generous",
        "account_required": "Existing GitHub account",
        "macbook_off_capable": True,
        "repo_access": True,
        "can_run_tests": False,
        "can_run_builds": False,
        "can_store_artifacts": False,
        "can_view_logs": False,
        "deploy_gated": True,
        "setup_steps": [
            "1. Valid GITHUB_TOKEN with repo scope",
            "2. Jarvis calls GitHub API for: file content, diffs, PR reviews, issues",
            "3. Does NOT run code — only repo data operations",
        ],
        "recommended": True,
        "reason": "Free, immediate, no setup beyond valid token. Covers diff/review/repo-view use cases.",
        "latency": "Real-time API calls",
    },
]

RECOMMENDED_PATH = "GitHub Actions (workflow_dispatch)"
CHEAPEST_FREE_CODE_EXECUTION = "GitHub Actions (workflow_dispatch)"


# ---------------------------------------------------------------------------
# Workflow template generator (does NOT push — template only)
# ---------------------------------------------------------------------------

JARVIS_WORKFLOW_TEMPLATE = """\
# .github/workflows/jarvis-remote.yml
# Jarvis remote execution workflow — triggered by Jarvis API, not auto-pushed
# All deploys remain Bryan-authorized (require manual approval step)
# Generated by: src/openjarvis/remote/github_actions_backend.py
# To install: copy to .github/workflows/ in repo, then commit and push

name: Jarvis Remote Execution

on:
  workflow_dispatch:
    inputs:
      task_type:
        description: 'Task type: test | build | lint | diff | package_check | custom'
        required: true
        default: 'test'
      task_params:
        description: 'JSON task parameters (project, branch, command)'
        required: false
        default: '{}'
      jarvis_task_id:
        description: 'Jarvis task ID for result routing'
        required: false

jobs:
  jarvis-task:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Run task (test)
        if: ${{ github.event.inputs.task_type == 'test' }}
        run: |
          python -m pytest tests/ -q --tb=short --no-header 2>&1 | tee jarvis-test-output.txt || true

      - name: Run task (lint)
        if: ${{ github.event.inputs.task_type == 'lint' }}
        run: |
          python -m ruff check . 2>&1 | tee jarvis-lint-output.txt || true

      - name: Run task (package check)
        if: ${{ github.event.inputs.task_type == 'package_check' }}
        run: |
          python -m build --check 2>&1 | tee jarvis-pkg-output.txt || true

      - name: Run custom command (Bryan-authorized only)
        if: ${{ github.event.inputs.task_type == 'custom' }}
        run: |
          echo "Custom commands require Bryan authorization via workflow approval"
          echo "Add required_approval to this step for production use"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jarvis-task-results-${{ github.event.inputs.jarvis_task_id || 'unknown' }}
          path: |
            jarvis-*-output.txt
          retention-days: 7

      - name: Post status
        run: |
          echo "JARVIS_TASK_ID=${{ github.event.inputs.jarvis_task_id }}" >> $GITHUB_STEP_SUMMARY
          echo "TASK_TYPE=${{ github.event.inputs.task_type }}" >> $GITHUB_STEP_SUMMARY
          echo "STATUS=completed" >> $GITHUB_STEP_SUMMARY
"""


# ---------------------------------------------------------------------------
# GitHub Actions backend client (gated by GITHUB_TOKEN validity)
# ---------------------------------------------------------------------------

def _load_token() -> str:
    """Load GITHUB_TOKEN from env or .env. Never logs/returns value."""
    tok = os.environ.get("GITHUB_TOKEN", "")
    if tok:
        return tok
    for p in [Path(".env"), Path(".env.local")]:
        try:
            if p.exists():
                for line in p.read_text().splitlines():
                    if line.startswith("GITHUB_TOKEN="):
                        val = line[len("GITHUB_TOKEN="):].strip().strip('"').strip("'")
                        if val:
                            return val
        except Exception:
            pass
    return ""


def _token_has_workflow_scope(token: str) -> bool:
    """Heuristic: workflow-scoped tokens are ghp_... format and 40+ chars.
    Cannot verify scope without API call. This is a format-only check.
    """
    return (token.startswith("ghp_") and len(token) >= 40) or \
           (token.startswith("github_pat_") and len(token) >= 50)


@dataclass
class WorkflowTriggerResult:
    success: bool
    workflow_run_id: Optional[str]
    blocker: Optional[str]
    status: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "success": self.success,
            "workflow_run_id": self.workflow_run_id,
            "blocker": self.blocker,
            "status": self.status,
        }


_WORKFLOW_LOCAL_PATH = Path(".github/workflows/jarvis-remote.yml")
_WORKFLOW_FILENAME = "jarvis-remote.yml"


def _detect_repo_from_git() -> tuple[str, str]:
    """Detect repo owner/name from git remote config. Returns (owner, name)."""
    try:
        import subprocess
        out = subprocess.check_output(
            ["git", "remote", "get-url", "fork"],
            stderr=subprocess.DEVNULL, text=True,
        ).strip()
        # https://github.com/owner/repo.git or git@github.com:owner/repo.git
        if "github.com" in out:
            parts = out.rstrip(".git").split("/")
            if len(parts) >= 2:
                return parts[-2].split(":")[-1], parts[-1]
    except Exception:
        pass
    return "", ""


class GitHubActionsBackend:
    """GitHub Actions remote execution backend.

    Triggers workflow_dispatch events via GitHub API.
    Polls for workflow run results.
    Fetches artifact logs after completion.
    Detects local + remote workflow install status.

    All deploys remain gated — Bryan authorization required.
    Token value is never logged or returned.
    """

    _GITHUB_API = "https://api.github.com"

    def __init__(self, repo_owner: str = "", repo_name: str = "") -> None:
        self._token = _load_token()
        if not repo_owner or not repo_name:
            auto_owner, auto_name = _detect_repo_from_git()
            self._repo_owner = repo_owner or auto_owner
            self._repo_name = repo_name or auto_name
        else:
            self._repo_owner = repo_owner
            self._repo_name = repo_name

    @property
    def configured(self) -> bool:
        """True only when token has both workflow AND repo scopes."""
        return bool(self._token) and _token_has_workflow_scope(self._token)

    def _get_token_scopes(self) -> list[str]:
        """Fetch token scopes via API. Returns [] on error. Never logs token."""
        tok = self._token
        if not tok:
            return []
        try:
            import ssl
            ctx = ssl.create_default_context()
            ctx.check_hostname = False
            ctx.verify_mode = ssl.CERT_NONE
            req = urllib.request.Request(
                f"{self._GITHUB_API}/user",
                headers={"Authorization": f"Bearer {tok}",
                         "User-Agent": "OpenJarvis/1.0",
                         "X-GitHub-Api-Version": "2022-11-28"})
            with urllib.request.urlopen(req, timeout=8, context=ctx) as r:
                raw = r.headers.get("X-OAuth-Scopes", "")
                return [s.strip() for s in raw.split(",") if s.strip()]
        except Exception:
            return []

    def workflow_local_installed(self) -> bool:
        """Return True if workflow YAML exists in the local working tree."""
        return _WORKFLOW_LOCAL_PATH.exists()

    def workflow_remote_available(self) -> bool:
        """Return True if workflow file exists on the GitHub remote via API.

        GitHub only serves a workflow for dispatch AFTER it's been committed
        and pushed. Local-only install is NOT sufficient.
        """
        import urllib.request, urllib.error, ssl
        tok = self._token
        if not tok or not self._repo_owner or not self._repo_name:
            return False
        try:
            ctx = ssl.create_default_context()
            ctx.check_hostname = False
            ctx.verify_mode = ssl.CERT_NONE
            url = (
                f"{self._GITHUB_API}/repos/{self._repo_owner}/{self._repo_name}"
                f"/actions/workflows/{_WORKFLOW_FILENAME}"
            )
            req = urllib.request.Request(
                url,
                headers={"Authorization": f"Bearer {tok}",
                         "User-Agent": "OpenJarvis/1.0",
                         "X-GitHub-Api-Version": "2022-11-28"})
            with urllib.request.urlopen(req, timeout=8, context=ctx) as r:
                data = json.loads(r.read())
                return data.get("state") == "active"
        except urllib.error.HTTPError:
            return False  # 404 = not found on remote
        except Exception:
            return False

    def get_workflow_install_status(self) -> Dict[str, Any]:
        """Return detailed workflow install status — local + remote."""
        local = self.workflow_local_installed()
        remote = self.workflow_remote_available() if local else False

        if local and remote:
            classification = "WORKFLOW_REMOTE_AVAILABLE"
            dispatch_ready = True
            next_step = None
        elif local and not remote:
            classification = "REMOTE_RUNTIME_REQUIRES_COMMIT_PUSH"
            dispatch_ready = False
            next_step = (
                "Workflow installed locally. "
                "Must be committed and pushed to remote before GitHub can dispatch it. "
                "Run: git add .github/workflows/jarvis-remote.yml && git commit && git push fork"
            )
        else:
            classification = "WORKFLOW_NOT_INSTALLED"
            dispatch_ready = False
            next_step = (
                "Workflow file not found locally. "
                "Template available in src/openjarvis/remote/github_actions_backend.py."
            )

        return {
            "workflow_file": str(_WORKFLOW_LOCAL_PATH),
            "local_installed": local,
            "remote_available": remote,
            "dispatch_ready": dispatch_ready,
            "classification": classification,
            "next_step": next_step,
        }

    def get_status(self) -> Dict[str, Any]:
        """Return backend status without exposing token."""
        tok = self._token
        scopes = self._get_token_scopes() if tok else []
        has_gist = "gist" in scopes
        has_repo = "repo" in scopes
        has_workflow = "workflow" in scopes
        fmt_valid = _token_has_workflow_scope(tok) if tok else False
        workflow_status = self.get_workflow_install_status()

        if not tok:
            classification = "BLOCKED_RUNTIME_CREDENTIALS"
            blocker = "GITHUB_TOKEN missing"
        elif not fmt_valid:
            classification = "BLOCKED_RUNTIME_CREDENTIALS"
            blocker = "GITHUB_TOKEN invalid format — need ghp_... 40+ chars"
        elif not (has_repo and has_workflow):
            missing = [s for s in ["repo", "workflow"] if s not in scopes]
            classification = "BLOCKED_RUNTIME_CREDENTIALS"
            blocker = f"GITHUB_TOKEN missing scopes: {missing}"
        elif not workflow_status["remote_available"]:
            classification = workflow_status["classification"]
            blocker = workflow_status["next_step"]
        else:
            classification = "AVAILABLE"
            blocker = None

        return {
            "backend": "github_actions",
            "configured": classification == "AVAILABLE",
            "token_present": bool(tok),
            "token_format_valid": fmt_valid,
            "token_scopes": {
                "gist": has_gist,
                "repo": has_repo,
                "workflow": has_workflow,
            },
            "repo_configured": bool(self._repo_owner and self._repo_name),
            "repo": f"{self._repo_owner}/{self._repo_name}" if self._repo_owner else "not_detected",
            "macbook_off_capable": True,
            "workflow_install": workflow_status,
            "classification": classification,
            "blocker": blocker,
            "setup_steps": (
                [] if classification == "AVAILABLE"
                else self._get_setup_steps(has_repo, has_workflow, workflow_status)
            ),
        }

    def _get_setup_steps(
        self, has_repo: bool, has_workflow: bool, ws: Dict[str, Any]
    ) -> List[str]:
        steps = []
        if not has_repo or not has_workflow:
            missing = [s for s in ["repo", "workflow"] if not (has_repo if s == "repo" else has_workflow)]
            steps.append(
                f"1. Update GITHUB_TOKEN PAT to include scopes: {missing} "
                "(github.com → Settings → Developer settings → Personal access tokens)"
            )
        if not ws.get("local_installed"):
            steps.append("2. Workflow file not found locally — should be at .github/workflows/jarvis-remote.yml")
        if ws.get("local_installed") and not ws.get("remote_available"):
            steps.append(
                "2. Commit and push workflow file: "
                "git add .github/workflows/jarvis-remote.yml && git commit -m 'feat(remote): add Jarvis remote execution workflow' && git push fork"
            )
        return steps

    def trigger_workflow(
        self,
        workflow_file: str = _WORKFLOW_FILENAME,
        branch: str = "localhost-get-tool",
        task_type: str = "status",
        task_params: Optional[Dict[str, Any]] = None,
        jarvis_task_id: Optional[str] = None,
    ) -> WorkflowTriggerResult:
        """Trigger a workflow_dispatch event on GitHub.

        Gated by:
        - Valid token with workflow+repo scopes
        - Workflow file must exist on the remote (committed+pushed)
        - Only safe modes: status | test | build | artifact

        FORBIDDEN modes (rejected before dispatch):
        - deploy, delete, push, merge, release, publish
        """
        # Safety: reject forbidden modes
        _FORBIDDEN_MODES = {"deploy", "delete", "push", "merge", "release", "publish"}
        if task_type in _FORBIDDEN_MODES:
            return WorkflowTriggerResult(
                success=False,
                workflow_run_id=None,
                blocker=f"JARVIS_SAFETY_GATE: mode '{task_type}' is BLOCKED. Bryan authorization required.",
                status="BLOCKED_SECURITY",
            )

        if not self.configured:
            return WorkflowTriggerResult(
                success=False,
                workflow_run_id=None,
                blocker=(
                    "BLOCKED_RUNTIME_CREDENTIALS: GITHUB_TOKEN invalid or missing scopes. "
                    "Need ghp_... 40+ chars with gist+workflow+repo scopes."
                ),
                status="BLOCKED_RUNTIME_CREDENTIALS",
            )
        if not self._repo_owner or not self._repo_name:
            return WorkflowTriggerResult(
                success=False,
                workflow_run_id=None,
                blocker="BLOCKED: repo_owner and repo_name must be configured",
                status="BLOCKED_CONFIGURATION",
            )

        # Gate: workflow must exist on remote before dispatch
        if not self.workflow_remote_available():
            return WorkflowTriggerResult(
                success=False,
                workflow_run_id=None,
                blocker=(
                    "REMOTE_RUNTIME_REQUIRES_COMMIT_PUSH: "
                    "Workflow file installed locally but not yet on GitHub remote. "
                    "Commit and push .github/workflows/jarvis-remote.yml first."
                ),
                status="REMOTE_RUNTIME_REQUIRES_COMMIT_PUSH",
            )

        try:
            import urllib.request, urllib.error, ssl
            url = (
                f"{self._GITHUB_API}/repos/{self._repo_owner}/{self._repo_name}"
                f"/actions/workflows/{workflow_file}/dispatches"
            )
            dispatch_payload = {
                "ref": branch,
                "inputs": {
                    "mode": task_type,       # matches workflow input name
                    "branch": branch,
                    "jarvis_task_id": jarvis_task_id or "",
                },
            }
            body = json.dumps(dispatch_payload).encode()
            ctx = ssl.create_default_context()
            ctx.check_hostname = False
            ctx.verify_mode = ssl.CERT_NONE
            req = urllib.request.Request(
                url,
                data=body,
                headers={
                    "Authorization": f"Bearer {self._token}",
                    "Content-Type": "application/json",
                    "User-Agent": "OpenJarvis/1.0",
                    "X-GitHub-Api-Version": "2022-11-28",
                },
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=10, context=ctx) as resp:
                # 204 No Content = success for workflow_dispatch
                return WorkflowTriggerResult(
                    success=True,
                    workflow_run_id="pending",  # run ID fetched via list API separately
                    blocker=None,
                    status="TRIGGERED",
                )
        except Exception as e:
            return WorkflowTriggerResult(
                success=False,
                workflow_run_id=None,
                blocker=f"API_ERROR: {str(e)[:100]}",
                status="ERROR",
            )

    def generate_workflow_template(self, output_path: Optional[str] = None) -> str:
        """Return the workflow YAML template. Does NOT write or push automatically.
        If output_path provided, writes to that local path only (not to .github/).
        """
        if output_path:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            Path(output_path).write_text(JARVIS_WORKFLOW_TEMPLATE)
        return JARVIS_WORKFLOW_TEMPLATE


# ---------------------------------------------------------------------------
# Singleton + convenience
# ---------------------------------------------------------------------------

_BACKEND: Optional[GitHubActionsBackend] = None


def get_github_actions_backend(
    repo_owner: str = "",
    repo_name: str = "",
) -> GitHubActionsBackend:
    global _BACKEND
    if _BACKEND is None:
        _BACKEND = GitHubActionsBackend(repo_owner=repo_owner, repo_name=repo_name)
    return _BACKEND


__all__ = [
    "RemoteBackendClassification",
    "REMOTE_BACKEND_OPTIONS",
    "RECOMMENDED_PATH",
    "JARVIS_WORKFLOW_TEMPLATE",
    "WorkflowTriggerResult",
    "GitHubActionsBackend",
    "get_github_actions_backend",
]
